# hindsight-test-repo/.github/workflows/fail.yml
name: Test and Lint Workflow

on: [push]

jobs:
  # This job will now PASS because we are not changing the test file
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run Python unit tests
        run: python -m unittest test_logic.py

  # This new job will FAIL because of the bad_code.py file
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install linter
        run: pip install flake8
      - name: Run linter
        run: flake8 .
