# hindsight-test-repo/.github/workflows/fail.yml
name: Realistic Test Failure Workflow

on: [push]

jobs:
  test-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run all unit tests
        # The 'discover' command automatically finds all files starting
        # with 'test_' and runs the tests inside them.
        run: python -m unittest discover
