# hindsight-test-repo/.github/workflows/fail.yml
name: Run Python Tests

on: [push]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Python unit tests
        run: python -m unittest test_logic.py
